version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bc
      POSTGRES_USER: bc
      POSTGRES_PASSWORD: bc
    volumes:
    - ./pg.sql:/docker-entrypoint-initdb.d/pg.sql
  nodejs:
    image: neuralegion/brokencrystals
    container_name: nodejs
    restart: always
    deploy:
      resources:
        limits:
          cpus: 3.5
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - db
  proxy:
    image: neuralegion/brokencrystals-client
    restart: always
    environment:
      CERTBOT_EMAIL: "anatol@neuralegion.com"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs
    volumes:
      - ./nginx-config:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
  watchtower:
    image: containrrr/watchtower
    restart: always
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --debug
volumes:
  letsencrypt:
